//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conffandauthh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class conferenceEntities2 : DbContext
    {
        public conferenceEntities2()
            : base("name=conferenceEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatHistory> ChatHistory { get; set; }
        public virtual DbSet<OldRooms> OldRooms { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<UsersInOldRoom> UsersInOldRoom { get; set; }
        public virtual DbSet<UsersInRoom> UsersInRoom { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<Invitation> Invitation { get; set; }
        public virtual DbSet<RoomsInvitations> RoomsInvitations { get; set; }
    }
}
