//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conffandauthh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatHistory
    {
        public int messageId { get; set; }
        public Nullable<int> oldRoomId { get; set; }
        public string roomname { get; set; }
        public string username { get; set; }
        public string userId { get; set; }
        public string content { get; set; }
    
        public virtual OldRooms OldRooms { get; set; }
    }
}
