//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conffandauthh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldRooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OldRooms()
        {
            this.ChatHistory = new HashSet<ChatHistory>();
            this.UsersInOldRoom = new HashSet<UsersInOldRoom>();
        }
    
        public int oldRoomId { get; set; }
        public string ownerId { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatHistory> ChatHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersInOldRoom> UsersInOldRoom { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
