//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conffandauthh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomsInvitations
    {
        public int invitationId { get; set; }
        public string inviterId { get; set; }
        public string invitee { get; set; }
    }
}
